#!/bin/bash

clear

CMD_PATH="$( dirname -- "$( readlink -f -- "$0"; )"; )"
ENV_FILE=$CMD_PATH/.env

if [[ ! -f "$ENV_FILE" ]]; then
    echo "#########################################################"
    echo "Debe existir un archivo .env con el siguiente contenido"
    echo
    echo "export USER=<user>"
    echo "export TOKEN=<gitlab user token>"
    echo 
    echo "#########################################################"
    exit
fi

source $ENV_FILE

COUNT=$#
REPOS="$@"

if (( $COUNT == 0 )); then
    echo "###################################################"
    echo "#"
    echo "# Debe indicar uno o más repositorios"
    echo "#"
    echo "###################################################"
    exit 1
fi

for REPO in "$REPOS"; do
    REPO=$(echo $REPO | sed "s/:/\//g")

    git_prefix=${REPO:0:3}
    https_prefix=${REPO:0:5}

    if [[ $git_prefix == "git" ]]; then
        URL="${REPO:4}"

    elif [[ $https_prefix == "https" ]]; then
        URL="${REPO:8}"
    else
        echo "###################################################"
        echo "#"
        echo "# la URL $REPO"
        echo "# no es válida debe iniciar con:"
        echo "#     git@ o con https://"
        echo "#"
        echo "###################################################"
        exit
    fi

    basename=$(basename $URL)
    echo $basename
    filename=${basename%.*}

    if [[ -d $filename ]]; then
        echo "Foelder $filename exists, repo no cloned"
        continue
    else
        URL="git clone https://${USER}:${TOKEN}@${URL}"
        $URL
        echo
        echo
    fi

done
